name: "RocketChat announcer 💬"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          job_name: 'Oi, pessoal, uma nova versão do Cuida foi publicada!'
          channel: '#TesteGithubActions'
          icon_emoji: 'https://framerusercontent.com/images/s79ZzWUDwmsYqL9DrfWrWIXaTHU.svg'
          commit: true
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
