name: "RocketChat announcer 💬"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':rocket: *Publish new release ${{ github.ref }}*'
          channel: '#TesteGithubActions'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
